categorical:
  features: ["S"]
  seq_len: [168]
  pred_len: [24]
  num_tokens: [1000]
  loss: ["MSE"]
  lradj: ["type1"]
  n_heads: [8]
  d_ff: [32]
  batch_size: [32]
  patch_len: [24]
  stride: [12]
  epochs: [10]
  llm_layers: [4]
  d_model: [64]
  dropout: [0.3]
  pct_start: [0.2]
  learning_rate: [0.03377044435573803]